### ISSUE TITLE
Since Meteor 2.11 - Exception in setTimeout callback: TypeError: fs.remove is not a function

### ISSUE THREAD

**Issue by Gobliins** [veliovgroup/Meteor-Files#870]
Hello,

after upgrading to Meteor 2.11 / Mongo 6, I get the mentioned error.

My Code, Serverside:

```
function loadFile() {
  ...
  return new Promise((resolve, reject) => {
    Files.load(loadUrl, options,
      (loadError, fileRef) => {
        if (loadError) {
          return reject({error: loadError});
        } else {
          return resolve({error: false, fileRef});
        }
      }, true);
  });
}
```
When i call this function with await, it never resolves nor rejects.
When using .then(), i get the described error:
```
Exception in setTimeout callback: TypeError: fs.remove is not a function
at onEnd (packages/ostrio:files/server.js:1433:18) 
at packages/ostrio:files/server.js:1480:13
at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)
at packages/meteor.js:587:25
at runWithEnvironment (packages/meteor.js:1417:24)
```

On Meteor 2.10 it was working ok.

Is there an update needed or has something changed with Promises in Node 14 / Meteor 2.11?

Edit:
Removed the promise code and worked with callbacks, but still hangs on Files.load().

**Comment by dr-dimitru** [comment]
@Gobliins confirmed as a bug, thank you; will follow up with fix shortly

**Comment by Gobliins** [comment]
Thx. If you need more info, just say. I just tested downgrading to Meteor 2.10. Code works as expected. It is running during Meteor startup BTW.

**Comment by Gobliins** [comment]
@dr-dimitru Thx for the fix. The error is not happening anymore. Unfortunately storing files is still not working in 2.11. No Entries inside the DB. On Filesystem I'm getting only 1KB files with plain text content: 503 - Service unavailable. 
However I'm not sure if this is a problem of meteor-files or the old CFS Packages retrieving the files.
We're currently migrating away from CFS.

**Comment by dr-dimitru** [comment]
@Gobliins have you figured it out?

**Comment by Gobliins** [comment]
Hey, I was on a break / weekend. Today I'm back on it. But I think it's a problem of the old Collection-FS, since I get a timeout during the Files.load() method. My Guess is, that there's a problem with the download URL also happens since Meteor 2.11.

**Comment by Gobliins** [comment]
@dr-dimitru  A little late but just wanted to tell you safe, it's not a problem of meteor-files :)

**Comment by dr-dimitru** [comment]
@Gobliins all good, thank you
